# This file was generated by GoReleaser. DO NOT EDIT.
cask "secret-proxy" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "50debd98122909022342aedc8c0313f145df33e53963b846299663ae0d73a822"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5d5af3037cb5960a6afc382a49c3035078da2c4539759e768b584f487085f891"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7eb82927dae3cc0846c5cda5315cfda7cdcac9df0b9d3fa05db50231648a3fd2"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c5f03259351ab84d9ff4a1fb591a3cdb961046958ef9d18400eed7a91ec7340b"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Linux_arm64.tar.gz"
    end
  end

  name "secret-proxy"
  desc "Local MITM proxy that swaps dummy placeholders for real secrets"
  homepage "https://github.com/githendrik/secret-proxy-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secret-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/secret-proxy"]
    end
  end

  # No zap stanza required

end
