# This file was generated by GoReleaser. DO NOT EDIT.
cask "secret-proxy" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "550d5a644596e58e4325f9ba72808412ba17a5ab0f4717c416d447782a9251f7"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "79f09c9802a380c1116974fbd119e78a7f723760e1cc887ca7a029a2a7c6afc0"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ed76e002b60a44346baed9015abe3878ba7d66773d18efd0fb4d7030d981a01"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "723fe69b6ac425467001866371b7ab18bcc052a067d6dadb562fa23145d3cc44"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Linux_arm64.tar.gz"
    end
  end

  name "secret-proxy"
  desc "Local MITM proxy that swaps dummy placeholders for real secrets"
  homepage "https://github.com/githendrik/secret-proxy-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secret-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/secret-proxy"]
    end
  end

  # No zap stanza required

end
