# This file was generated by GoReleaser. DO NOT EDIT.
cask "secret-proxy" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bee1ffab8d731f122ced970d7ad4e58b82ba6979a34c22a32517e316712849a2"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5ca7674637da0f1785916455de660d68c9a93ee8a2e56c47457a1053080b7d3f"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbd63456abc68c722d5cf56e198ee49a99beeb60d8e3f1c75be30e16ebf8e6f0"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "55f191c191bd24cc9fa568655fba15b689a142822441917e2b9f8111f455bb33"
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v#{version}/secret-proxy_Linux_arm64.tar.gz"
    end
  end

  name "secret-proxy"
  desc "Local MITM proxy that swaps dummy placeholders for real secrets"
  homepage "https://github.com/githendrik/secret-proxy-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secret-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/secret-proxy"]
    end
  end

  # No zap stanza required

end
