# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KiroProxy < Formula
  desc "Kiro API Proxy - OpenAI-compatible proxy for Kiro"
  homepage "https://github.com/githendrik/kiro-proxy-go"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.10/kiro-proxy_Darwin_x86_64.tar.gz"
      sha256 "c5406e70cebb5fa1882af05079a7882d938d29660317994dcad52b3ba2f9f33b"

      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.10/kiro-proxy_Darwin_arm64.tar.gz"
      sha256 "eea03ddd5447422b3e4926bfff71a58b2c8f4d7de2665ca09528c6fcf31df0fe"

      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.10/kiro-proxy_Linux_x86_64.tar.gz"
      sha256 "b81f816ea741dcc88dd04cdb739d9cab386c601c52d17e4587a609cb2fc0b7e4"
      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.10/kiro-proxy_Linux_arm64.tar.gz"
      sha256 "1de95a004e2a22a0f426451a272decffcda5134d798407452102c88925b00e2d"
      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
  end

  test do
    system "#{bin}/kiro-proxy", "--help"
  end
end
