# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KiroProxy < Formula
  desc "Kiro API Proxy - OpenAI-compatible proxy for Kiro"
  homepage "https://github.com/githendrik/kiro-proxy-go"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.7/kiro-proxy_Darwin_x86_64.tar.gz"
      sha256 "6ee167c45ed3214c4bc83368c752d5406618cfcecde3bf07c0e8026d4d91f92b"

      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.7/kiro-proxy_Darwin_arm64.tar.gz"
      sha256 "05fafb43fac3b8289e1e34aeab585d41e5dcec38c7fe41d2767ef93b01247410"

      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.7/kiro-proxy_Linux_x86_64.tar.gz"
      sha256 "37e5b9ae5145bc93dd4b8be6ed76ad02f4d2433584ef8ccff80e482cbd2e41c4"
      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.7/kiro-proxy_Linux_arm64.tar.gz"
      sha256 "2dc5d63bfe2d11adadc4f03ec0793388e4d0d0a86a1ddc8eb1960efc6fdff83e"
      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
  end

  test do
    system "#{bin}/kiro-proxy", "--help"
  end
end
