# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KiroProxy < Formula
  desc "Kiro API Proxy - OpenAI-compatible proxy for Kiro"
  homepage "https://github.com/githendrik/kiro-proxy-go"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.0/kiro-proxy_Darwin_x86_64.tar.gz"
      sha256 "22aefdda8eb06685bb53e106943a9779d7e4f83948c2d5111cf483701037b3ff"

      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.0/kiro-proxy_Darwin_arm64.tar.gz"
      sha256 "6606d0517cab2ae913181e82c2123da9b25c627f1c4e57a1923366371bd9eea2"

      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.0/kiro-proxy_Linux_x86_64.tar.gz"
      sha256 "75a957596b94b56bc39476242ad68225a7ff703d3543448b068b0cc806181321"
      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/githendrik/kiro-proxy-go/releases/download/v0.1.0/kiro-proxy_Linux_arm64.tar.gz"
      sha256 "02f7652b0ad731ec47def33dd1af01c2e521bd6ea6645327b2a19422f234f6ad"
      define_method(:install) do
        bin.install "kiro-proxy"
      end
    end
  end

  test do
    system "#{bin}/kiro-proxy", "--help"
  end
end
