# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretProxy < Formula
  desc "Local MITM proxy that swaps dummy placeholders for real secrets"
  homepage "https://github.com/githendrik/secret-proxy-go"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v0.0.1/secret-proxy_Darwin_x86_64.tar.gz"
      sha256 "0d61a9867d7bacb010f83e070acc1926f360b160aab9709fe8311e7d77582192"

      define_method(:install) do
        bin.install "secret-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v0.0.1/secret-proxy_Darwin_arm64.tar.gz"
      sha256 "427d2142a41a2fddeedcf38c716238560fcde1d2df130e93f3ebf5e88c27af0f"

      define_method(:install) do
        bin.install "secret-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v0.0.1/secret-proxy_Linux_x86_64.tar.gz"
      sha256 "ff1c7def9dcff316fa982fbc7d93e5319212894373fd8496e76bf2224fa19048"
      define_method(:install) do
        bin.install "secret-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/githendrik/secret-proxy-go/releases/download/v0.0.1/secret-proxy_Linux_arm64.tar.gz"
      sha256 "867e3574e9553c0f06efa69def9516bc5a12df1da02645e9c07f52de550e7a3b"
      define_method(:install) do
        bin.install "secret-proxy"
      end
    end
  end

  test do
    system "#{bin}/secret-proxy", "version"
  end
end
